# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(DT)
library(janitor)
library(plotly)
library(readxl)
library(rhino)
library(shiny.fluent)
library(shinyjs)
library(treesitter)
library(treesitter.r)
